database:
  driver: sqlite  # sqlite | postgres | mysql

  # SQLite 
  name: /data/tracker.db # (tracker.db)
  
  # PostgreSQL/MySQL
  host: localhost
  port: 5432
  user: postgres
  password: ""    # .env
  sslmode: disable
  
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 1h

server:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

auth:
  jwt_algorithm: "HS256" # HS256 | ES256 | RS256
  jwt_secret: ""      # .env
  jwt_private_key: "" # .env
  jwt_public_key: "" # .env
  jwt_key_id: "key-1"
  jwt_expiry: 24h
  jwt_refresh_expiry: 168h #Refresh token - 7 days

  cookie_secure: false
  cookie_name_access: access_token
  cookie_name_refresh: refresh_token
  cookie_domain : ""
  cookie_path: /

logging:
  level: info
  format: text  # text | json
